#!/usr/bin/env bash

pipeline_slug='tracker/monorepo-example'
branch='master'
num_builds=5
query="query PassedBuildsOnMasterQuery { pipeline(slug: \\\"${pipeline_slug}\\\") { builds(branch: \\\"${branch}\\\", state: [PASSED], last: ${num_builds}) { edges { node { commit url } } } } }"
curl https://graphql.buildkite.com/v1 \
  -H "Authorization: Bearer ${TOKEN}" \
  -d "{ \"query\": \"${query}\" }"
